Make player able to grab Big Bass bomb while fusing
fishfolk/punchy pull request #291
Opened 2023-01-04 07:20 UTC by Zac8668

Closes #280

2023-01-04 07:22 UTC, Zac8668 commented
For now I just made the bomb animation fps longer, until we make a bigger animation to extend the time for the player to grab the bomb.

2023-01-10 23:29 UTC, odecay requested changes
I think this is looking good, will test to make sure everything is working as expected.

2023-01-10 23:29 UTC, odecay commented on assets/items/bomb/bomb.item.yaml
> +    animation_fps: 1.
```suggestion
    //TODO: return and find another way to extend duration after animation system changes
    animation_fps: 1.
```

2023-01-10 23:29 UTC, odecay commented on src/fighter_state.rs
> +                                commands.entity(fighter_ent).add_child(item_ent);
I like the new way of doing Holding by adding as child. :+1: 
Nice job simplifying.

2023-01-11 03:45 UTC, odecay approved these changes

2023-01-12 15:59 UTC, odecay commented
Getting panic I *think* when the boss tries to throw a bomb.

```
thread 'Compute Task Pool (4)' panicked at 'Fighter has no item', src/fighter_state.rs:1372:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/otis/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.9.1/src/task_pool.rs:273:45
```

Is there a YAML property that is missing for the boss in this PR?

2023-01-14 03:38 UTC, odecay approved these changes

2023-01-14 03:40 UTC, odecay commented
bors merge

2023-01-14 03:48 UTC, merged